language: c

matrix:
  include:
    - os: linux
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python judy libarchive; fi
  - pip install --user cpp-coveralls

addons:
  apt:
    packages:
    - libarchive-dev
    - libjudy-dev
    - pkg-config

script:
  - ./waf configure
  - ./waf build
  - ./waf test

after_success:
  - coveralls --include src --build-root build/test/ --gcov-options '\-lp'
